FROM --platform=linux/amd64 ubuntu:latest
WORKDIR /usr/src/app
RUN mkdir -p /bun
COPY . .
RUN apt-get update
RUN apt-get install curl unzip -y
RUN curl --fail --location --progress-bar --output "/bun/bun.zip" "https://github.com/Jarred-Sumner/bun/releases/download/bun-v0.1.2/bun-linux-x64.zip"
RUN unzip -d /bun -q -o "/bun/bun.zip"
RUN mv /bun/bun-linux-x64/bun /usr/local/bin/bun
RUN chmod 777 /usr/local/bin/bun
RUN bun install
EXPOSE 3000
CMD bun run start